export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        surface: '#111827',
        'on-surface': '#ffffff',
        'on-background': '#ffffff',
        'surface-container': '#111827',
        'surface-container-low': '#030712',
        'surface-container-lowest': '#000000',
        'surface-container-high': '#1f2937',
        'surface-container-highest': '#374151',
        'surface-variant': '#1f2937',
        'on-surface-variant': '#9ca3af',
        outline: '#374151',
        'outline-variant': '#4b5563',
        'on-primary': '#030712',
        'primary-container': 'rgba(0, 245, 212, 0.1)',
        'on-primary-container': '#00F5D4',
        'on-secondary': '#030712',
        'secondary-container': 'rgba(0, 187, 249, 0.1)',
        'on-secondary-container': '#00BBF9',
        warning: '#FACC15',
        error: '#ef4444',
        'on-error': '#ffffff',
        'error-container': 'rgba(239, 68, 68, 0.1)',
        'on-error-container': '#ef4444',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1440px',
        gutter: '24px',
        'sidebar-width': '280px',
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'label-sm': ['Geist'],
        'body-md': ['Inter'],
        display: ['Geist'],
        'headline-lg': ['Geist'],
        'headline-md': ['Geist'],
        'headline-lg-mobile': ['Geist'],
        'label-md': ['Geist'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
}
